import * as AllSpells from './gameObject/spells/index.js';

export const ChampionPreset = {
  yasuo: {
    name: 'Yasuo',
    avatar: 'champ_yasuo',
    spells: [
      AllSpells.Heal,
      AllSpells.Yasuo_Q,
      AllSpells.Yasuo_W,
      AllSpells.Yasuo_E,
      AllSpells.Yasuo_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  lux: {
    name: 'Lux',
    avatar: 'champ_lux',
    spells: [
      AllSpells.Heal,
      AllSpells.Lux_Q,
      AllSpells.Yasuo_W,
      AllSpells.Lux_E,
      AllSpells.Lux_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  blitzcrank: {
    name: 'Blitzcrank',
    avatar: 'champ_blitzcrank',
    spells: [
      AllSpells.Heal,
      AllSpells.Blitzcrank_Q,
      AllSpells.Blitzcrank_W,
      AllSpells.Veigar_E,
      AllSpells.Blitzcrank_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  ashe: {
    name: 'Ashe',
    avatar: 'champ_ashe',
    spells: [
      AllSpells.Heal,
      AllSpells.Ashe_W,
      AllSpells.Ashe_W,
      AllSpells.Yasuo_W,
      AllSpells.Ashe_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  teemo: {
    name: 'Teemo',
    avatar: 'champ_teemo',
    spells: [
      AllSpells.Heal,
      AllSpells.Blitzcrank_Q,
      AllSpells.Blitzcrank_W,
      AllSpells.Teemo_R,
      AllSpells.Teemo_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  leblanc: {
    name: 'Leblanc',
    avatar: 'champ_leblanc',
    spells: [
      AllSpells.Heal,
      AllSpells.Blitzcrank_Q,
      AllSpells.Leblanc_W,
      AllSpells.Leblanc_E,
      AllSpells.Leblanc_W,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  leesin: {
    name: 'Lee Sin',
    avatar: 'champ_leesin',
    spells: [
      AllSpells.Heal,
      AllSpells.LeeSin_Q,
      AllSpells.LeeSin_Q,
      AllSpells.LeeSin_E,
      AllSpells.LeeSin_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  chogath: {
    name: 'Cho Gath',
    avatar: 'champ_chogath',
    spells: [
      AllSpells.Heal,
      AllSpells.ChoGath_Q,
      AllSpells.ChoGath_W,
      AllSpells.Yasuo_E,
      AllSpells.Yasuo_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  ahri: {
    name: 'Ahri',
    avatar: 'champ_ahri',
    spells: [
      AllSpells.Heal,
      AllSpells.Ahri_Q,
      AllSpells.Ahri_W,
      AllSpells.Ahri_E,
      AllSpells.Ahri_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  shaco: {
    name: 'Shaco',
    avatar: 'champ_shaco',
    spells: [
      AllSpells.Heal,
      AllSpells.Shaco_Q,
      AllSpells.Shaco_W,
      AllSpells.Shaco_E,
      AllSpells.Shaco_R,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
  olaf: {
    name: 'Olaf',
    avatar: 'champ_olaf',
    spells: [
      AllSpells.Heal,
      AllSpells.Olaf_Q,
      AllSpells.Olaf_Q,
      AllSpells.Olaf_Q,
      AllSpells.Olaf_Q,
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  },
};

export const getChampionPresetRandom = () => {
  return {
    name: 'Random',
    avatar: random(Object.values(ChampionPreset).map(x => x.avatar)),
    spells: [
      AllSpells.Heal,
      ...Array.from({ length: 4 })
        .fill(0)
        .map(() => {
          return random(Object.values(AllSpells));
        }),
      AllSpells.Flash,
      AllSpells.Ghost,
    ],
  };
};

export const getRandomChampionPreset = () => {
  const keys = Object.keys(ChampionPreset);
  const randomKey = keys[Math.floor(Math.random() * keys.length)];
  return ChampionPreset[randomKey];
};

export const SpellGroups = [
  {
    name: 'Yasuo',
    image: 'champ_yasuo',
    spells: [AllSpells.Yasuo_Q, AllSpells.Yasuo_W, AllSpells.Yasuo_E, AllSpells.Yasuo_R],
  },
  {
    name: 'Shaco',
    image: 'champ_shaco',
    spells: [AllSpells.Shaco_Q, AllSpells.Shaco_W, AllSpells.Shaco_E, AllSpells.Shaco_R],
  },
  {
    name: 'Ahri',
    image: 'champ_ahri',
    spells: [AllSpells.Ahri_Q, AllSpells.Ahri_W, AllSpells.Ahri_E, AllSpells.Ahri_R],
  },
  {
    name: 'Lee Sin',
    image: 'champ_leesin',
    spells: [AllSpells.LeeSin_Q, AllSpells.LeeSin_E, AllSpells.LeeSin_R],
  },
  {
    name: 'Blitzcrank',
    image: 'champ_blitzcrank',
    spells: [AllSpells.Blitzcrank_Q, AllSpells.Blitzcrank_W, AllSpells.Blitzcrank_R],
  },
  {
    name: 'Lux',
    image: 'champ_lux',
    spells: [AllSpells.Lux_Q, AllSpells.Lux_E, AllSpells.Lux_R],
  },
  {
    name: 'Ashe',
    image: 'champ_ashe',
    spells: [AllSpells.Ashe_W, AllSpells.Ashe_R],
  },
  {
    name: "Cho'Gath",
    image: 'champ_chogath',
    spells: [AllSpells.ChoGath_Q, AllSpells.ChoGath_W],
  },
  {
    name: 'Leblanc',
    image: 'champ_leblanc',
    spells: [AllSpells.Leblanc_W, AllSpells.Leblanc_E],
  },
  {
    name: 'Malphite',
    image: 'champ_malphite',
    spells: [AllSpells.Malphite_R],
  },
  {
    name: 'Olaf',
    image: 'champ_olaf',
    spells: [AllSpells.Olaf_Q],
  },

  {
    name: 'Teemo',
    image: 'champ_teemo',
    spells: [AllSpells.Teemo_R],
  },
  {
    name: 'Veigar',
    image: 'champ_veigar',
    spells: [AllSpells.Veigar_E],
  },

  {
    name: 'Zed',
    image: 'champ_zed',
    spells: [AllSpells.Zed_W],
  },
  {
    name: 'Phép Bổ Trợ',
    image: '',
    spells: [AllSpells.Flash, AllSpells.Ghost, AllSpells.Heal, AllSpells.StealthWard],
  },
];

export const MonsterPreset = {
  baron: {
    name: 'Baron',
    avatar: 'monster_Baron_Nashor',
    camp: {
      x: 2147,
      y: 1876,
      r: 100,
    },
    speed: 0,
    size: 100,
    attackRange: 400,
    reviveTime: 3000,
    health: 1000,
  },
  blue1: {
    name: 'Blue',
    avatar: 'monster_Blue_Sentinel',
    camp: {
      x: 1631,
      y: 2958,
      r: 300,
    },
    speed: 2,
    size: 80,
    attackRange: 50,
    reviveTime: 3000,
    health: 300,
  },
  blue2: {
    name: 'Blue',
    avatar: 'monster_Blue_Sentinel',
    camp: {
      x: 4794,
      y: 3419,
      r: 300,
    },
    speed: 2,
    size: 80,
    attackRange: 50,
    reviveTime: 3000,
    health: 300,
  },
  red1: {
    name: 'Red',
    avatar: 'monster_Red_Brambleback',
    camp: {
      x: 3368,
      y: 4698,
      r: 300,
    },
    speed: 2,
    size: 80,
    attackRange: 50,
    reviveTime: 3000,
    health: 300,
  },
  red2: {
    name: 'Red',
    avatar: 'monster_Red_Brambleback',
    camp: {
      x: 3085,
      y: 1672,
      r: 300,
    },
    speed: 2,
    size: 80,
    attackRange: 50,
    reviveTime: 3000,
    health: 300,
  },
  wolf1: {
    name: 'Greater Wolf',
    avatar: 'monster_Greater_Murk_Wolf',
    camp: {
      x: 1685,
      y: 3562,
      r: 300,
    },
    speed: 2,
    size: 70,
    attackRange: 50,
    reviveTime: 3000,
    health: 300,
  },
  wolf1_a: {
    name: 'Wolf',
    avatar: 'monster_Murk_Wolf',
    camp: {
      x: 1602,
      y: 3511,
      r: 300,
    },
    speed: 2.5,
    size: 40,
    attackRange: 50,
    reviveTime: 3000,
    health: 100,
  },
  wolf1_b: {
    name: 'Wolf',
    avatar: 'monster_Murk_Wolf',
    camp: {
      x: 1725,
      y: 3659,
      r: 300,
    },
    speed: 2.5,
    size: 40,
    attackRange: 50,
    reviveTime: 3000,
    health: 100,
  },
  wolf2: {
    name: 'Greater Wolf',
    avatar: 'monster_Greater_Murk_Wolf',
    camp: {
      x: 4728,
      y: 2835,
      r: 300,
    },
    speed: 2,
    size: 70,
    attackRange: 50,
    reviveTime: 3000,
    health: 300,
  },
  wolf2_a: {
    name: 'Wolf',
    avatar: 'monster_Murk_Wolf',
    camp: {
      x: 4709,
      y: 2743,
      r: 300,
    },
    speed: 2.5,
    size: 40,
    attackRange: 50,
    reviveTime: 3000,
    health: 100,
  },
  wolf2_b: {
    name: 'Wolf',
    avatar: 'monster_Murk_Wolf',
    camp: {
      x: 4816,
      y: 2888,
      r: 300,
    },
    speed: 2.5,
    size: 40,
    attackRange: 50,
    reviveTime: 3000,
    health: 100,
  },
  gomp1: {
    name: 'Gromp',
    avatar: 'monster_Gromp',
    camp: {
      x: 914,
      y: 2784,
      r: 300,
    },
    speed: 2,
    size: 70,
    attackRange: 150,
    reviveTime: 3000,
    health: 300,
  },
  gomp2: {
    name: 'Gromp',
    avatar: 'monster_Gromp',
    camp: {
      x: 5540,
      y: 3599,
      r: 300,
    },
    speed: 2,
    size: 70,
    attackRange: 150,
    reviveTime: 3000,
    health: 300,
  },
  raptor1: {
    name: 'Crimson_Raptor',
    avatar: 'monster_Crimson_Raptor',
    camp: {
      x: 2954,
      y: 4110,
      r: 300,
    },
    speed: 2,
    size: 70,
    attackRange: 150,
    reviveTime: 3000,
    health: 300,
  },
  raptor1_a: {
    name: 'Raptor',
    avatar: 'monster_Raptor',
    camp: {
      x: 3045,
      y: 4026,
      r: 300,
    },
    speed: 2,
    size: 40,
    attackRange: 150,
    reviveTime: 3000,
    health: 50,
  },
  raptor1_b: {
    name: 'Raptor',
    avatar: 'monster_Raptor',
    camp: {
      x: 3149,
      y: 4095,
      r: 300,
    },
    speed: 2,
    size: 40,
    attackRange: 150,
    reviveTime: 3000,
    health: 50,
  },
  raptor1_c: {
    name: 'Raptor',
    avatar: 'monster_Raptor',
    camp: {
      x: 3060,
      y: 4169,
      r: 300,
    },
    speed: 2,
    size: 40,
    attackRange: 150,
    reviveTime: 3000,
    health: 50,
  },
  raptor2: {
    name: 'Crimson_Raptor',
    avatar: 'monster_Crimson_Raptor',
    camp: {
      x: 3498,
      y: 2258,
      r: 300,
    },
    speed: 2,
    size: 70,
    attackRange: 150,
    reviveTime: 3000,
    health: 300,
  },
  raptor2_a: {
    name: 'Raptor',
    avatar: 'monster_Raptor',
    camp: {
      x: 3432,
      y: 2356,
      r: 300,
    },
    speed: 2,
    size: 40,
    attackRange: 150,
    reviveTime: 3000,
    health: 50,
  },
  raptor2_b: {
    name: 'Raptor',
    avatar: 'monster_Raptor',
    camp: {
      x: 3307,
      y: 2295,
      r: 300,
    },
    speed: 2,
    size: 40,
    attackRange: 150,
    reviveTime: 3000,
    health: 50,
  },
  raptor2_c: {
    name: 'Raptor',
    avatar: 'monster_Raptor',
    camp: {
      x: 3378,
      y: 2183,
      r: 300,
    },
    speed: 2,
    size: 40,
    attackRange: 150,
    reviveTime: 3000,
    health: 50,
  },
};
