/**
 * `packs/riot/`'s own asset-manifest generator — walks this pack's own
 * `assets/` and writes this pack's own `generated/assetManifest.ts`.
 *
 * A duplicate of core's `scripts/generate-assets.mjs`, not an import of it.
 * The survey behind this task (`docs/superpowers/surveys/2026-08-22-pack-
 * package-boundary.md` §4) measured that walk as having zero core
 * dependency — no Vite, no `ContentApi`, no `AssetManager`, just
 * `node:fs`/`node:path` — so duplicating it here, rather than reaching back
 * into core, is what lets this generator run standing entirely on its own:
 * as a workspace package today, or as a sibling repository with no core
 * checkout beside it tomorrow. Compare `scripts/generate-catalog.mjs` next
 * to this file, which invokes *core's* catalogue generator by name instead
 * of copying it — that one genuinely can't stand alone, because it needs a
 * real `ContentApi` to construct a spell and read its fields.
 *
 * `root` is computed from this file's own location (`resolve(dirname(...),
 * '..')`, one level up from `packs/riot/scripts/`), the same trick core's
 * own script uses for itself — so this needs no CLI flag or environment
 * variable to find the pack's root, in this monorepo or after extraction.
 *
 *   npm run assets:generate     # rewrite generated/assetManifest.ts
 *   npm run assets:check        # fail if it is stale (runs in verify:all)
 */
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, extname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const IMAGE_EXTENSIONS = new Set(['.gif', '.jpeg', '.jpg', '.png', '.svg', '.webp']);
const AUDIO_EXTENSIONS = new Set(['.mp3', '.ogg', '.wav']);
const URL_EXTENSIONS = new Set(['.cur']);

/** This pack's own tree: walk `assets/`, write `generated/assetManifest.ts`. */
const ASSETS_DIR = 'assets';
const OUTPUT_PATH = 'generated/assetManifest.ts';
const REGENERATE_COMMAND = 'npm run assets:generate';

function normalizePart(value) {
  return value.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

// Identical to core's own `assetKeyForPath` (`scripts/generate-assets.mjs`)
// on purpose: the pack's asset keys must keep the exact shape they had
// before this generator moved, and this function is what produces them.
export function assetKeyForPath(inputPath) {
  const path = inputPath.replaceAll('\\', '/');
  const withoutExtension = path.slice(0, -extname(path).length);
  const relativePath = withoutExtension.replace(/^.*?assets\//, '');
  const parts = relativePath.split('/');

  if (parts[0] === 'images') parts.shift();

  let prefix = normalizePart(parts.shift() ?? 'asset');
  if (prefix === 'champions') {
    prefix = parts[0] === 'background' ? `champ_${normalizePart(parts.shift())}` : 'champ';
  } else {
    prefix =
      {
        buffs: 'buff',
        cursors: 'cursor',
        monsters: 'monster',
        objects: 'obj',
        others: 'other',
        screenshots: 'screenshot',
        sounds: 'sound',
        spells: 'spell',
      }[prefix] ?? prefix;
  }

  return [prefix, ...parts.map(normalizePart)].filter(Boolean).join('_');
}

function assetKind(path) {
  const extension = extname(path).toLowerCase();
  if (IMAGE_EXTENSIONS.has(extension)) return 'image';
  if (extension === '.json') return 'json';
  if (AUDIO_EXTENSIONS.has(extension)) return 'audio';
  if (URL_EXTENSIONS.has(extension)) return 'url';
  throw new Error(`Unsupported asset file: ${path}`);
}

export function buildManifestEntries(paths) {
  const entries = paths
    .map(path => path.replaceAll('\\', '/'))
    .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0))
    .map(path => ({ key: assetKeyForPath(path), kind: assetKind(path), path }));
  const seen = new Map();

  for (const entry of entries) {
    const duplicate = seen.get(entry.key);
    if (duplicate) {
      throw new Error(`Duplicate asset key "${entry.key}": ${duplicate}, ${entry.path}`);
    }
    seen.set(entry.key, entry.path);
  }

  return entries;
}

/**
 * `importPrefix` is how far the generated file has to walk, from its own
 * directory, back to `root` — every entry's `path` is written relative to
 * that. `'../'` for `generated/assetManifest.ts` (one segment down from this
 * pack's own root).
 */
export function renderManifest(entries, { importPrefix = '../' } = {}) {
  const imports = entries.map((entry, index) => {
    const importPath = `${importPrefix}${entry.path}?url`;
    return `import asset${index}Url from '${importPath}';`;
  });
  const records = entries.map(
    (entry, index) =>
      `  ${JSON.stringify(entry.key)}: { kind: '${entry.kind}', url: asset${index}Url, path: ${JSON.stringify(entry.path)} },`
  );

  return [
    '// Generated by scripts/generate-assets.mjs. Do not edit.',
    ...imports,
    '',
    "export type AssetKind = 'image' | 'json' | 'audio' | 'url';",
    '',
    'export const assetManifest = {',
    ...records,
    '} as const;',
    '',
    'export type AssetKey = keyof typeof assetManifest;',
    '',
  ].join('\n');
}

async function walk(directory, root) {
  const paths = [];
  const entries = await readdir(directory, { withFileTypes: true }).catch(error => {
    if (error.code === 'ENOENT') return [];
    throw error;
  });
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    const absolutePath = resolve(directory, entry.name);
    if (entry.isDirectory()) paths.push(...(await walk(absolutePath, root)));
    else paths.push(relative(root, absolutePath).replaceAll('\\', '/'));
  }
  return paths;
}

function importPrefixFor(root, outputPath) {
  const outputDir = dirname(resolve(root, outputPath));
  const toRoot = relative(outputDir, root).replaceAll('\\', '/');
  return toRoot === '' ? './' : `${toRoot}/`;
}

export async function renderAssetManifestSource(root, { add = [], remove = [] } = {}) {
  const paths = new Set(await walk(resolve(root, ASSETS_DIR), root));
  for (const path of remove) paths.delete(path.replaceAll('\\', '/'));
  for (const path of add) {
    const normalized = path.replaceAll('\\', '/');
    if (normalized.startsWith(`${ASSETS_DIR}/`)) paths.add(normalized);
  }
  const entries = buildManifestEntries([...paths]);
  return renderManifest(entries, { importPrefix: importPrefixFor(root, OUTPUT_PATH) });
}

export async function generate(root, check = false) {
  const outputPath = resolve(root, OUTPUT_PATH);
  const source = await renderAssetManifestSource(root);

  if (check) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== source)
      throw new Error(`Generated asset manifest is stale. Run ${REGENERATE_COMMAND}.`);
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source);
}

const scriptPath = fileURLToPath(import.meta.url);
if (process.argv[1] && resolve(process.argv[1]) === scriptPath) {
  const root = resolve(dirname(scriptPath), '..');
  generate(root, process.argv.includes('--check')).catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
