const BuffAddType = {
  REPLACE_EXISTING: 'REPLACE_EXISTING',
  RENEW_EXISTING: 'RENEW_EXISTING',
  STACKS_AND_RENEWS: 'STACKS_AND_RENEWS',
  STACKS_AND_CONTINUE: 'STACKS_AND_CONTINUE',
  STACKS_AND_OVERLAPS: 'STACKS_AND_OVERLAPS',
};

Object.freeze(BuffAddType);

export default BuffAddType;
