import type { ContentApi } from './ContentApi';
import type { MonsterAbility } from '@/game/gameObject/attackableUnits/Monster';

/** Re-exported so a pack may `import type { MonsterAbility } from '@/content/types'`. */
export type { MonsterAbility };

/**
 * What a content pack is, and why the code half is a function.
 *
 * A pack's contract splits into a data half (`ContentPackData` — manifest,
 * champions, spell display, monsters, maps: read to draw a picker) and a code
 * half (`ContentPackCode` — spells, monster abilities: real engine classes).
 * `ContentPack`, the union every existing reader still names, is their
 * intersection.
 *
 * The code half stays a factory taking core's API, because the alternative is
 * a pack that bundles its own copy of `Spell`, `SpellObject` and the buffs —
 * and then there are two classes of every name in the process. `instanceof`
 * stops answering, `Z_INDEX_MAP` is looked up by base-class identity so a
 * pack's spell object matches no key and falls to z-index 99 on top of every
 * champion, and the buff registry exists twice. One core, handed in.
 *
 * The reason the split exists at all: reading a pack's *data* — its champion
 * list, a map to offer in a picker — used to mean building that whole engine
 * surface first, because the one function a pack exported needed the api to
 * run. A menu screen that only wants names and icons now never has to.
 *
 * The same shape also loads at runtime, which is the whole point:
 *
 *     Stage 1  import code from '@moba2d/content-riot'         -> code(api)
 *     Stage 2  const { default: code } = await import(url)     -> code(api)
 *
 * so batch 2 changes `install.ts` and nothing a pack author wrote.
 */
export type ContentPackFactory = (api: ContentApi) => ContentPackCode;

export interface PackManifest {
  /** A bare identifier. It becomes the prefix in every `<packId>:<localId>`. */
  id: string;
  version: string;
  /** Which core versions this pack was built against. */
  coreRange: string;
  /**
   * The base a pack's own asset keys are namespaced under, or absent for a
   * pack that ships no art tree of its own.
   *
   * **Same question `qualify()` already answered, asked one field over.**
   * `ChampionEntry.image`, `MonsterBody.avatar` and `SpellDisplayData.iconKey`
   * are each documented "pack-relative" — a bare, local key the pack author
   * writes without knowing what any other installed pack calls its own art
   * (`'champ_yasuo'`, never `'riot:champ_yasuo'`). Two packs can each declare
   * a champion whose portrait is locally `'hero'`, and nothing before this
   * field told those two apart: both keys landed in one flat `AssetManager`
   * namespace, so whichever pack's `assets:generate` ran last — or merely
   * loaded last — silently won every collision. The fix is the identical
   * shape `qualify(packId, localId)` already uses everywhere else in this
   * file (spell ids, champion ids, monster ids, map ids): `PackRegistry.writeData`
   * rewrites `image`/`avatar`/`iconKey` into `<assets>:<localKey>` the same
   * way it rewrites `id`/`spells`/`recall`, and `AssetManager` resolves that
   * qualified form against exactly the one pack's own registered asset
   * manifest — see `AssetManager.registerPackAssets`'s own doc comment for
   * the resolve side of this same crossing. A second, independent
   * convention (say, folding the base into the key string by hand, the way
   * `packs/reference/spells/*.ts`'s `'reference_vera_q'` keys do today by
   * accident of their own folder name) was rejected on purpose: a codebase
   * with two ways to spell "which pack does this belong to" has neither.
   *
   * **Optional, not required, and the two states mean different things.**
   * `undefined` is not "this pack forgot to declare its assets" — it is
   * "this pack's `image`/`avatar`/`iconKey` strings, if it has any, are
   * already keys in *core's* flat namespace and must resolve there
   * unqualified." The reference pack is exactly this today: its five files
   * still live under core's own `assets/images/reference/`, so qualifying
   * its `iconKey`s here would turn a working `'reference_vera_q'` into a
   * broken `'reference:reference_vera_q'` that resolves nowhere. Setting
   * this field is what a pack does *after* moving its art into its own tree
   * (`packs/<id>/assets/`, generated by `assets:generate --tree=<id>`) —
   * `packs/riot`'s own manifest sets `assets: 'riot'` for exactly that
   * reason, once its 378 files stopped living in core's tree.
   *
   * Always equal to `id` in every pack this repository ships. A pack's
   * asset namespace and its content namespace are the same question, and a
   * separately-settable string here would let a future pack quietly desync
   * them for no reason a reader could ever recover — this field exists
   * anyway, rather than every asset-resolving call site reusing `id`
   * directly, so "does this pack ship real art" is a single yes/no a reader
   * (and `PackRegistry.writeData`) can see at a glance instead of having to
   * ask "does a `packs/<id>/assets/` directory happen to exist."
   */
  assets?: string;
}

/** A spell class. Loose on purpose — `spellRegistry.SpellClass` is `any` too. */
export type SpellClass = new (...args: never[]) => unknown;

/** A spell class that has not been fetched yet. Resolved at most once. */
export type SpellLoader = () => Promise<SpellClass>;

/**
 * How a pack hands over a spell.
 *
 * A class outright for a small pack; a thunk for a large one. The Riot pack is
 * 240 spells behind `src/generated/spellModules.ts`'s dynamic imports, and
 * handing those over eagerly would put every spell in the game into the first
 * chunk a match downloads — a chunking optimisation this codebase already made
 * once, on purpose, and which nothing in a type would have caught being undone.
 */
export type SpellSource = SpellClass | SpellLoader;

/**
 * Marks a `SpellLoader` explicitly, rather than asking `PackRegistry` to guess.
 *
 * The obvious discriminator — a class has a `prototype`, a loader does not —
 * is only half true: an arrow-function loader indeed has none (an arrow
 * function can never be a class, full stop), but a pack author who writes an
 * ordinary `function` expression as a loader gets one too, and it would be
 * misread as the spell class itself. `PackRegistry` trusts the no-`prototype`
 * case unconditionally and otherwise requires this mark before treating a
 * function as a loader; wrap a `function`-expression loader in `lazy()` and it
 * is read correctly.
 */
const SPELL_LOADER_MARK: unique symbol = Symbol('lol2d.content.spellLoader');

export function lazy(load: SpellLoader): SpellSource {
  return Object.assign(load, { [SPELL_LOADER_MARK]: true as const });
}

/**
 * True when `source` is a loader — a bare arrow function (which structurally
 * can never be a class) or anything wrapped by `lazy()`. Exported for
 * `PackRegistry`, the only reader of `SPELL_LOADER_MARK`.
 */
export function isSpellLoader(source: SpellSource): source is SpellLoader {
  if (typeof source !== 'function') return false;
  if (source.prototype === undefined) return true;
  return (source as unknown as Record<symbol, unknown>)[SPELL_LOADER_MARK] === true;
}

export interface ChampionEntry {
  id: string;
  name: string;
  /** Pack-relative asset key, or null for a champion with no portrait yet. */
  image: string | null;
  /** Local spell ids, in slot order. */
  spells: string[];
  /** Local id of this champion's way home. Absent on a map that grants none. */
  recall?: string;
  /**
   * Whether the pregame screen may offer this as a champion.
   *
   * `false` is the normal answer for a shelf — a group of loose abilities, or
   * a one-ability stub that exists only to widen the random pool. Core used to
   * decide this by testing whether the portrait key started with `champ_`,
   * which is a naming convention no pack has any reason to share.
   */
  playable: boolean;
  /** Basic-attack profile. Omitted means core's `DEFAULT_CHAMPION_ATTACK`. */
  attack?: ChampionAttack;
  /**
   * True for the one roster row whose `spells` are this pack's own D/F
   * options — the summoner-spell shelf, not a champion. `playable: false`
   * cannot mark it on its own: every partial champion stub (a one-ability
   * shelf kept only to widen the random pool) is `playable: false` too, and
   * matching this shelf by its display name would break the same way
   * `playable` itself used to (see that field's own doc comment) the moment
   * a translation changed the label. Declared, like `playable`, so core can
   * find the D/F shelf without naming a single spell of its own.
   */
  summonerShelf?: boolean;
}

/**
 * One spell's display fields, as data.
 *
 * Field-for-field the same shape `src/generated/spellCatalog.ts` produces, and
 * that is not a coincidence: the pregame screen renders a whole roster without
 * loading a single spell class, and it can only keep doing that if a pack's
 * spells arrive as data too. A pack repo generates this with its own
 * `spell-catalog` command (spec §9) exactly the way core generates its own.
 *
 * `iconKey` is a plain string, not core's generated `AssetKey` union — a
 * pack's art is its own and its keys type-check inside its own build.
 */
export interface SpellDisplayData {
  name: string;
  /** Vietnamese HTML — `<span class="damage">`/`.buff`/`.time`/plain `<span>`. */
  description: string;
  iconKey: string | null;
  /** The spell's own tuning number, before match rules. */
  coolDownMs: number;
  /** The spell's own tuning number, before match rules. */
  manaCost: number;
  /** `castSpec.cooldown.durationMs` — what a countdown runs before CDR. */
  specCoolDownMs: number;
}

/** A champion's basic-attack profile. Absent means core's default. */
export interface ChampionAttack {
  damage: number;
  attacksPerSecond: number;
  range: number;
}

/**
 * One body of a camp — a camp is a **composition** of these, not N identical
 * copies of one. A wolf pit is a Greater Wolf plus two Wolves, visibly
 * different sprites and sizes; collapsing that to `count: 3` of one body was
 * this field's first (wrong) shape — see `MonsterDef`'s own doc comment.
 *
 * `offset` places a body relative to its slot's centre — `NeutralSlot`
 * carries only where the *camp* sits, never an individual body, so a
 * multi-body camp needs its own internal layout. `{0, 0}` is the common case
 * for a camp of one (a jungle boss, a buff camp, a small camp).
 */
export interface MonsterBody {
  name: string;
  /** Pack-relative asset key. */
  avatar: string;
  speed: number;
  size: number;
  attackRange: number;
  reviveTime: number;
  health: number;
  /** Per swing. Defaults to a share of `health` when omitted. */
  damage?: number;
  /** ms between swings. Defaults to 1500 when omitted. */
  attackInterval?: number;
  /** Champions this close wake the camp. Defaults to `attackRange + 120`. */
  aggroRange?: number;
  /** This body's position relative to the slot's `{x, y}`. */
  offset: { x: number; y: number };
}

/**
 * A monster, as a pack declares it — enough for `Game.spawnJungle()` to build
 * every real `Monster` a neutral slot needs once its `role` has resolved to
 * one of these.
 *
 * `members` replaces an earlier shape that put one flat set of tuning plus a
 * `count` directly on `MonsterDef` — collapsing a wolf pit (a Greater Wolf
 * and two Wolves: different avatars, different sizes, different health) into
 * three identical bodies. `monstersFilling(role)` answering with
 * **alternatives** — several packs offering something for the same role,
 * install order deciding — is a different question from **composition** —
 * what a single camp is made of — and `count` conflated the two. A camp of
 * three wolves is one `MonsterDef` with three `MonsterBody` entries, the way
 * it actually was before position and identity were split apart.
 *
 * Deliberately **not** `abilities` on `MonsterBody` — those are engine code
 * (`MonsterAbility` callbacks), the same reason a champion's kit is a spell
 * *id* here and never a class. A monster's abilities arrive through the
 * pack's code half instead — `ContentPackCode.monsterAbilities`, keyed by
 * local monster id exactly the way `spells` is keyed by local spell id — and
 * `preset.ts`'s `monsterBodyPreset` merges them back on by reading
 * `contentRegistry().abilitiesFor(monster.id)`, never by importing a
 * specific pack's file. This pack's one boss monster is the first
 * and, as of this writing, only monster that supplies any.
 */
export interface MonsterDef {
  id: string;
  name: string;
  /** Slot roles this monster can occupy. Free strings; core only matches. */
  fills: string[];
  /** What this camp is made of. Never empty — a camp of one is one entry. */
  members: MonsterBody[];
}

export interface Faction {
  id: string;
}

export interface SpawnSlot {
  faction: string;
  x: number;
  y: number;
  r: number;
}

export interface MinionSlot {
  faction: string;
  lane: string;
  x: number;
  y: number;
  /**
   * How far a released minion may be scattered around this point, so a wave
   * does not spawn six bodies stacked on one coordinate for
   * `UnitCollisionSystem` to shove apart. Absent means no scatter.
   *
   * Deliberately per-slot rather than a shared engine constant: the old
   * `MUSTER_SCATTER_PX` was sized to stay under the gap between Summoner's
   * Rift's own two base turrets, a fact about that map's geometry, not a
   * rule every map shares. A map author who declares the point is the one
   * who can see whether it needs a scatter radius, and how big.
   */
  scatter?: number;
}

/** Core's own vocabulary — `Turret` and `Fountain` are core classes. */
export type StructureKind = 'turret';

export interface StructureSlot {
  faction: string;
  kind: StructureKind;
  x: number;
  y: number;
}

export interface NeutralSlot {
  /** A free string a monster's `fills` matches. Core never interprets it. */
  role: string;
  x: number;
  y: number;
  r: number;
}

export interface LaneDefinition {
  id: string;
  from: string;
  to: string;
  waypoints: { x: number; y: number }[];
}

/**
 * A map's cheap half: enough to list, name and describe a world to a picker.
 * `PackRegistry.maps()` returns exactly this, qualified — never the polygons.
 */
export interface MapSummary {
  id: string;
  name: string;
  /** Square edge length in world units. */
  size: number;
  factions: Faction[];
}

/**
 * A map's heavy half: terrain to route and collide against, and the slots
 * fountains, turrets, jungle camps and minions occupy. Fetched only once a
 * match is actually starting — see `MapGeometrySource`.
 */
export interface MapGeometry {
  terrain: {
    wall: { x: number; y: number }[][];
    bush: { x: number; y: number }[][];
    water: { x: number; y: number }[][];
  };
  slots: {
    spawn: SpawnSlot[];
    minion: MinionSlot[];
    structure: StructureSlot[];
    neutral: NeutralSlot[];
  };
  /** Absent on a map with no lanes — no waves, and PUSH falls through. */
  lanes?: LaneDefinition[];
}

/** A map's geometry that has not been fetched yet. Resolved at most once. */
export type MapGeometryLoader = () => Promise<MapGeometry>;

/**
 * How a pack hands over a map's heavy half.
 *
 * A plain object for a small map; a loader for one the size of Summoner's
 * Rift — 395 polygons a menu screen has no business downloading before it has
 * even drawn a picker. See `SpellSource`'s own doc comment; the shape and the
 * reason are identical, one level up.
 */
export type MapGeometrySource = MapGeometry | MapGeometryLoader;

/**
 * A map, as a pack declares it — the eager `MapSummary` a picker lists, plus
 * the (possibly lazy) `geometry` a match actually plays on.
 *
 * Split the way `SpellSource` already splits a spell class from its loader,
 * for the same reason: `size`/`name`/`factions` cost nothing to hold in the
 * menu's own chunk, and `geometry` — the terrain, the slots, the lanes — is
 * the one payload in the whole pack contract bigger than everything else in
 * it combined. See `packs/riot/maps/summonersRift.ts` for the worked
 * example: its own module holds only the summary, and `geometry` is
 * `() => import('./summonersRiftGeometry')`.
 */
export interface MapDefinition extends MapSummary {
  geometry: MapGeometrySource;
}

/**
 * A map with its geometry already resolved — what `Game` and `TerrainMap`
 * are actually handed once `PackRegistry.loadMapGeometry` has settled.
 * `GameScene.startGame()` is what guarantees that has happened before
 * `new Game(...)` runs; see its own doc comment.
 */
export type ActiveMap = MapSummary & MapGeometry;

/**
 * Everything about a pack that a picker can render without the engine: no
 * spell class, no `ContentApi`, nothing that needs `Spell`/`SpellObject` in
 * scope. `PackRegistry.installData` writes exactly this, and `contentCatalog()`
 * installs only this — see that module's own header for why that closure
 * matters.
 */
export interface ContentPackData {
  manifest: PackManifest;
  champions?: ChampionEntry[];
  /** Keyed by *local* spell id — the same keys as `ContentPackCode.spells`. */
  spellDisplay?: Record<string, SpellDisplayData>;
  monsters?: Record<string, MonsterDef>;
  maps?: MapDefinition[];
}

/**
 * The half of a pack that is real engine classes, and the only half a
 * `ContentPackFactory` ever hands back — see that type's own doc comment for
 * why it still needs the api even though the data half no longer does.
 *
 * `monsterAbilities` is a distinct field from `ContentPackData.monsters`
 * rather than a same-named `abilities` addition to it — the two are keyed by
 * local monster id but hold different halves (tuning data vs. real classes),
 * and `ContentPack = ContentPackData & ContentPackCode` would otherwise
 * require one property to answer to two incompatible types. See
 * `MonsterBody`'s own doc comment for why abilities live here instead of on
 * `MonsterBody`/`MonsterDef` in the first place.
 */
export interface ContentPackCode {
  spells?: Record<string, SpellSource>;
  /** Keyed by *local* monster id — the same keys as `ContentPackData.monsters`. */
  monsterAbilities?: Record<string, MonsterAbility[]>;
}

/**
 * The whole pack, as every reader from before the split still names it —
 * `PackRegistry.install()` takes one, and both halves' fields stay optional
 * exactly as they were, since an intersection of two interfaces with only
 * optional fields is satisfied by either half alone.
 */
export type ContentPack = ContentPackData & ContentPackCode;

export const STRUCTURE_KINDS: readonly StructureKind[] = Object.freeze(['turret']);
