import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, extname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const IMAGE_EXTENSIONS = new Set(['.gif', '.jpeg', '.jpg', '.png', '.svg', '.webp']);
const AUDIO_EXTENSIONS = new Set(['.mp3', '.ogg', '.wav']);
const URL_EXTENSIONS = new Set(['.cur']);
const LEGACY_SOURCE_FILES = new Set(['assets/sounds/index.js']);

function normalizePart(value) {
  return value.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

export function assetKeyForPath(inputPath) {
  const path = inputPath.replaceAll('\\', '/');
  const withoutExtension = path.slice(0, -extname(path).length);
  const relativePath = withoutExtension.replace(/^.*?assets\//, '');
  const parts = relativePath.split('/');

  if (parts[0] === 'images') parts.shift();

  let prefix = normalizePart(parts.shift() ?? 'asset');
  if (prefix === 'champions') {
    prefix = parts[0] === 'background' ? `champ_${normalizePart(parts.shift())}` : 'champ';
  } else {
    prefix = {
      buffs: 'buff',
      cursors: 'cursor',
      monsters: 'monster',
      objects: 'obj',
      others: 'other',
      screenshots: 'screenshot',
      sounds: 'sound',
      spells: 'spell',
    }[prefix] ?? prefix;
  }

  return [prefix, ...parts.map(normalizePart)].filter(Boolean).join('_');
}

function assetKind(path) {
  const extension = extname(path).toLowerCase();
  if (IMAGE_EXTENSIONS.has(extension)) return 'image';
  if (extension === '.json') return 'json';
  if (AUDIO_EXTENSIONS.has(extension)) return 'audio';
  if (URL_EXTENSIONS.has(extension)) return 'url';
  throw new Error(`Unsupported asset file: ${path}`);
}

export function buildManifestEntries(paths) {
  const entries = paths
    .map(path => path.replaceAll('\\', '/'))
    .sort((left, right) => left < right ? -1 : left > right ? 1 : 0)
    .map(path => ({ key: assetKeyForPath(path), kind: assetKind(path), path }));
  const seen = new Map();

  for (const entry of entries) {
    const duplicate = seen.get(entry.key);
    if (duplicate) {
      throw new Error(`Duplicate asset key "${entry.key}": ${duplicate}, ${entry.path}`);
    }
    seen.set(entry.key, entry.path);
  }

  return entries;
}

export function renderManifest(entries) {
  const imports = entries.map((entry, index) => {
    const importPath = `../../${entry.path}?url`;
    return `import asset${index}Url from '${importPath}';`;
  });
  const records = entries.map((entry, index) =>
    `  ${JSON.stringify(entry.key)}: { kind: '${entry.kind}', url: asset${index}Url, path: ${JSON.stringify(entry.path)} },`
  );

  return [
    '// Generated by scripts/generate-assets.mjs. Do not edit.',
    ...imports,
    '',
    "export type AssetKind = 'image' | 'json' | 'audio' | 'url';",
    '',
    'export const assetManifest = {',
    ...records,
    '} as const;',
    '',
    'export type AssetKey = keyof typeof assetManifest;',
    '',
  ].join('\n');
}

async function walk(directory, root) {
  const paths = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const absolutePath = resolve(directory, entry.name);
    if (entry.isDirectory()) paths.push(...await walk(absolutePath, root));
    else {
      const path = relative(root, absolutePath).replaceAll('\\', '/');
      if (!LEGACY_SOURCE_FILES.has(path)) paths.push(path);
    }
  }
  return paths;
}

export async function generate(root, check = false) {
  const outputPath = resolve(root, 'src/generated/assetManifest.ts');
  const source = renderManifest(buildManifestEntries(await walk(resolve(root, 'assets'), root)));

  if (check) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== source) throw new Error('Generated asset manifest is stale. Run npm run assets:generate.');
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source);
}

const scriptPath = fileURLToPath(import.meta.url);
if (process.argv[1] && resolve(process.argv[1]) === scriptPath) {
  const root = resolve(dirname(scriptPath), '..');
  generate(root, process.argv.includes('--check')).catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
