import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, extname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const IMAGE_EXTENSIONS = new Set(['.gif', '.jpeg', '.jpg', '.png', '.svg', '.webp']);
const AUDIO_EXTENSIONS = new Set(['.mp3', '.ogg', '.wav']);
const URL_EXTENSIONS = new Set(['.cur']);
/**
 * Files under `assets/` the manifest must never mint a key for, even though
 * `walk()` would otherwise find them.
 *
 *  - `assets/sounds/index.js` is a legacy source file that happens to sit
 *    under `assets/`, not an asset — it was never meant to gain a `?url`
 *    import.
 *  - `assets/json/summoner_map.json` *is* a real asset, but
 *    `src/content/maps/summonersRiftGeometry.ts` reads it directly as raw
 *    text (a `?raw` import, parsed as JSON in that module — see its own
 *    header for why not through `AssetManager`), and nothing has read it
 *    through `AssetManager`/`assetManifest` since Task 5 moved the map off
 *    `preset.ts`'s old synchronous asset lookup. Left in, the generator kept
 *    minting a `json_summoner_map` entry nobody called — a second, separate
 *    `?url` import of the same 22,180 bytes, so a production build emitted
 *    `dist/assets/summoner_map-*.json` and the service worker precached it,
 *    on top of the identical bytes already inlined into
 *    `map-summonersrift-*.js` by the `?raw` import. A first offline install
 *    downloaded the map twice.
 */
const MANIFEST_EXCLUDED_FILES = new Set([
  'assets/sounds/index.js',
  'assets/json/summoner_map.json',
]);

function normalizePart(value) {
  return value.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

export function assetKeyForPath(inputPath) {
  const path = inputPath.replaceAll('\\', '/');
  const withoutExtension = path.slice(0, -extname(path).length);
  const relativePath = withoutExtension.replace(/^.*?assets\//, '');
  const parts = relativePath.split('/');

  if (parts[0] === 'images') parts.shift();

  let prefix = normalizePart(parts.shift() ?? 'asset');
  if (prefix === 'champions') {
    prefix = parts[0] === 'background' ? `champ_${normalizePart(parts.shift())}` : 'champ';
  } else {
    prefix =
      {
        buffs: 'buff',
        cursors: 'cursor',
        monsters: 'monster',
        objects: 'obj',
        others: 'other',
        screenshots: 'screenshot',
        sounds: 'sound',
        spells: 'spell',
      }[prefix] ?? prefix;
  }

  return [prefix, ...parts.map(normalizePart)].filter(Boolean).join('_');
}

function assetKind(path) {
  const extension = extname(path).toLowerCase();
  if (IMAGE_EXTENSIONS.has(extension)) return 'image';
  if (extension === '.json') return 'json';
  if (AUDIO_EXTENSIONS.has(extension)) return 'audio';
  if (URL_EXTENSIONS.has(extension)) return 'url';
  throw new Error(`Unsupported asset file: ${path}`);
}

export function buildManifestEntries(paths) {
  const entries = paths
    .map(path => path.replaceAll('\\', '/'))
    .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0))
    .map(path => ({ key: assetKeyForPath(path), kind: assetKind(path), path }));
  const seen = new Map();

  for (const entry of entries) {
    const duplicate = seen.get(entry.key);
    if (duplicate) {
      throw new Error(`Duplicate asset key "${entry.key}": ${duplicate}, ${entry.path}`);
    }
    seen.set(entry.key, entry.path);
  }

  return entries;
}

export function renderManifest(entries) {
  const imports = entries.map((entry, index) => {
    const importPath = `../../${entry.path}?url`;
    return `import asset${index}Url from '${importPath}';`;
  });
  const records = entries.map(
    (entry, index) =>
      `  ${JSON.stringify(entry.key)}: { kind: '${entry.kind}', url: asset${index}Url, path: ${JSON.stringify(entry.path)} },`
  );

  return [
    '// Generated by scripts/generate-assets.mjs. Do not edit.',
    ...imports,
    '',
    "export type AssetKind = 'image' | 'json' | 'audio' | 'url';",
    '',
    'export const assetManifest = {',
    ...records,
    '} as const;',
    '',
    'export type AssetKey = keyof typeof assetManifest;',
    '',
  ].join('\n');
}

async function walk(directory, root) {
  const paths = [];
  const entries = await readdir(directory, { withFileTypes: true }).catch(error => {
    if (error.code === 'ENOENT') return [];
    throw error;
  });
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    const absolutePath = resolve(directory, entry.name);
    if (entry.isDirectory()) paths.push(...(await walk(absolutePath, root)));
    else {
      const path = relative(root, absolutePath).replaceAll('\\', '/');
      if (!MANIFEST_EXCLUDED_FILES.has(path)) paths.push(path);
    }
  }
  return paths;
}

export async function renderAssetManifestSource(root, { add = [], remove = [] } = {}) {
  const paths = new Set(await walk(resolve(root, 'assets'), root));
  for (const path of remove) paths.delete(path.replaceAll('\\', '/'));
  for (const path of add) {
    const normalized = path.replaceAll('\\', '/');
    if (normalized.startsWith('assets/') && !MANIFEST_EXCLUDED_FILES.has(normalized))
      paths.add(normalized);
  }
  return renderManifest(buildManifestEntries([...paths]));
}

export async function generate(root, check = false) {
  const outputPath = resolve(root, 'src/generated/assetManifest.ts');
  const source = await renderAssetManifestSource(root);

  if (check) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== source)
      throw new Error('Generated asset manifest is stale. Run npm run assets:generate.');
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source);
}

const scriptPath = fileURLToPath(import.meta.url);
if (process.argv[1] && resolve(process.argv[1]) === scriptPath) {
  const root = resolve(dirname(scriptPath), '..');
  generate(root, process.argv.includes('--check')).catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
